version: '3.7'
services:
  web:
    image: 'ubuntu:20.04'
    build:
      dockerfile: './nginx.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '11080:80'
      - '11022:22'
      - '3000:3000'
    volumes:
      - './app:/app'