version: '3.7'
services:
  web:
    image: 'ubuntu:20.04'
    build:
      dockerfile: './web.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '11080:80'
      - '11022:22'
      - '13001:3001'
    volumes:
      - './app:/app'
      - './nginx/sites-available:/etc/nginx/sites-available'