version: '3.7'
services:
  front-web:
    image: 'ubuntu:14.04'
    build:
      dockerfile: './front-web/nginx.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '11080:80'
      - '11022:22'
      - '11443:443'
    volumes:
      - './front-web/nginx/http.conf:/etc/nginx/http.conf'
      - './front-web/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './front-web/nginx/mime.types:/etc/nginx/mime.types'
      - './front-web/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf'
      - './front-web/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf'
      - './front-web/php/php.ini:/usr/local/php/etc/php.ini'
      - './front-web/php/check_permission_utf8.php:/etc/check_permission_utf8.php'
      - './front-web/php/GREENSHIELD_utf8.php:/etc/GREENSHIELD_utf8.php'
      - './front-web/mysoho.test:/home/dev-httpd' # 프론트 root
      - './front-web/logs/:/backup/logs/' # 프론트 root
    networks:
      new:
        aliases:
          - mysoho.test
  front-db:
    image: grugnog/mysql-5.1:latest
    build:
      dockerfile: './front-db/mysql.Dockerfile'
    ports:
      - '12306:3306'
      - '12022:22'
    environment:
      - 'MYSQL_DATABASE=front'
      - 'MYSQL_ROOT_PASSWORD=docker123'
      - 'TZ=Asia/Seoul'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
    volumes:
      - './front-db/mysql:/var/lib/mysql'
    networks:
      - new
  sellercenter-web:
    image: 'ubuntu:20.04'
    build:
      dockerfile: './sellercenter-web/web.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '13080:80'
      - '13022:22'
    volumes:
      - './sellercenter-web/nginx/http.conf:/etc/nginx/http.conf'
      - './sellercenter-web/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './sellercenter-web/nginx/mysoho-dev.conf:/etc/nginx/mysoho-dev.conf'
      - './sellercenter-web/nginx/sites-available:/etc/nginx/sites-available'
      - './sellercenter-web/php/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf'
      - './sellercenter-web/php/php.ini:/etc/php/7.1/fpm/php.ini'
      - './sellercenter-web/php/check_permission_utf8.php:/etc/check_permission_utf8.php'
      - './sellercenter-web/php/GREENSHIELD_utf8.php:/etc/GREENSHIELD_utf8.php'
      - './sellercenter-web/heojun.mysoho.test:/home/heojun.mysoho.test' # 판매자센터 root
      - './sellercenter-web/heojun.mysoho.db:/home/heojun.mysoho.db' # 판매자센터db root
      - './sellercenter-web/mysoho.db:/home/mysoho.db' # 프론트db root
      - './sellercenter-web/logs/:/backup/logs/'
    networks:
      new:
        aliases:
          - heojun.mysoho.test
  sellercenter-db:
    image: mysql:5.7.18
    build:
      dockerfile: './sellercenter-db/mysql.Dockerfile'
    ports:
      - '14306:3306'
      - '14022:22'
    environment:
      - MYSQL_DATABASE=sellercenter
      - MYSQL_ROOT_PASSWORD=docker123
      - TZ=Asia/Seoul
    volumes:
      - ./sellercenter-db/mysql:/var/lib/mysql
    networks:
      - new
  redis:
    image: redis:4.0.14-alpine
    networks:
      - new
networks:
  new: